services:
  - name: pdf-merger
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
